# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  admin_email: "example@gmail.com"
  admin_password: 123456
  admin_username: "Admin"
  admin_role: "admin"
  secret_key_base: 48fd6053d1096be03367137a2a998d9dc8b71b16c33643a1fa16aa9a117082e60efe2bd3ad230ea66bf2f1d724a505f45fd5f4a8b6f0d6475848bf2abf7317d6

test:
  secret_key_base: 35f30f00427ae318e579a1fc38efbdff9cb0c840855d2ae819bb4221292466c0ce6f56829ccc7257093bb4075a4f543694908c878cba55c00b31791fe11d4397

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
